{% set version = "3.2.5" %}

package:
  name: flopy
  version: {{ version }}

source:
  fn: flopy-{{ version }}.tar.gz
  url: https://github.com/modflowpy/flopy/archive/{{ version }}.tar.gz
  sha256: d062ef6b9da54e567bbc9c7f5241ef4828c346d749fc4b9443b11b37381bf8ae

build:
  number: 0
  script: python setup.py install --single-version-externally-managed  --record record.txt

requirements:
  build:
    - python
    - setuptools
    - numpy
    - matplotlib
  run:
    - python
    - numpy
    - matplotlib

test:
  imports:
    - flopy

about:
  home: https://github.com/modflowpy/flopy
  license: BSD 3-Clause
  summary: 'FloPy is a Python package for developing, running, and post-processing MODFLOW-based models.'

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
    - jdhughes-usgs
