travis:
  secure:
    BINSTAR_TOKEN: cyejrJzbs+cJcp8lH7QWXYGJhzgYya6r2JS8j9cm1/FJJFWh5ge6KdO+uVR8UxYwbS0On5XD0QzLgaWL+g/OWlgQ697tZljmyojLpUSmNkPx1C2+n8fVaUkz4ZQ5+OwIeDG07Q7gjLFz6GBF+qVgW0Lb1xguUbFbfIHKwaIZXgbuD0rrOi+1lFyP/HxACefUswfov8FQfi2YbuZJfdWYyZwnYDLzVKtWVCuQbrY8RvQDIQhXWzL/k5IZEAKOKWOoz08cjkJE/BGeItDc8lxqHeU8VtXzGXFMOV4qRFz7P2UYHQXXEiQawni6IosFkfD0qyLSO/FOeStahe6IrWkDc5yKtrzfYAbClWTi71JEZcgWhZxCz79+OYX+Kjm3/kWyg3LBeLnZSNYz/9mm/uvfzuQxx+lYjqgz31Wzp4eCpAq6bHKw+fQ2P19prfBMLLpan7KTl+ur52uGSmkblpayh+Kxn1HHvvBUpUBl8U+HgNbU2eFmaLb2/azS6nt4BA5bLuNyMqdSkBT0SrXY2BKB3Ecpcj1zlQKV4CD+PmPWXuX1BvdzAvTCJeN7f2mdpS5JWnP/JJa2tN3O8JIsKNQLN2yW20g7mtoc6C64EfThLDPnHlq24n70ErRU9KzN+h8sbFpOTW7Dc7zmLTd9BTjgEp+3RfoYATIAhuaVQIfwAkw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
